name: nuwa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.7"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.2
  injectable: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  device_preview: ^1.2.0
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Inter/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900



flutter_intl:
  enabled: true
